# -*- coding: utf-8 -*-
"""Major Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcWuQROH_Yyil_8it0dspduZu7SVPaCe
"""

!pip install nltk
#IMPORTING LIBRARIES AND DATA
import nltk
nltk.download('vader_lexicon')

from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()
#CREATING CHAT INTERFACE
def chat():
    print("Chatbot: Hi there! How can I help you today?")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'exit':
            print("Chatbot: Goodbye!")
            break
        analyze_sentiment(user_input)
#USER INPUT IS ANALYSIED USING IMPORTED FUNCTION
def analyze_sentiment(user_input):
    sentiment_scores = sia.polarity_scores(user_input)
    sentiment = sentiment_scores['compound']

    if sentiment >= 0.05:
        print("Chatbot: That sounds positive!")
    elif sentiment <= -0.05:
        print("Chatbot: That seems negative.")
    else:
        print("Chatbot: I sense a neutral sentiment.")

if __name__ == "__main__":
    chat()